# Generated by Django 4.1.7 on 2023-03-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_name_about_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
